#!/usr/bin/env node
/**
 * Generate a bundled, self-contained TypeScript module from the on-disk XARF
 * schemas.
 *
 * The library validates against the official xarf-spec JSON schemas. Rather
 * than read those files from disk at runtime (which is fragile in bundled,
 * serverless, and edge environments where `fs`/`__dirname` are unreliable, and
 * which previously required a network fetch on install), we inline the schemas
 * into `src/schemas.generated.ts` at maintenance time. The generated module is
 * committed to the repository and imported directly, so the published package
 * carries the schemas with zero filesystem or network dependency.
 *
 * Run this whenever the configured `xarfSpec.version` changes, after
 * `npm run fetch-schemas` has refreshed the local `schemas/` directory:
 *
 *   npm run sync-schemas   # fetch-schemas && generate-schemas
 */

const fs = require('fs');
const path = require('path');

const SCHEMAS_DIR = path.join(__dirname, '..', 'schemas');
const TYPES_DIR = path.join(SCHEMAS_DIR, 'types');
const OUTPUT_FILE = path.join(__dirname, '..', 'src', 'schemas.generated.ts');
const VERSION_FILE = path.join(SCHEMAS_DIR, '.version');

/**
 * Read and parse a JSON schema file.
 * @param {string} filePath - Absolute path to the schema file
 * @returns {object} Parsed schema
 */
function readJson(filePath) {
  return JSON.parse(fs.readFileSync(filePath, 'utf-8'));
}

/**
 * Collect every schema file keyed by its relative path within the schemas dir.
 * Keys match the relative `$ref` paths used inside the schemas, e.g.
 * "xarf-core.json" and "types/messaging-spam.json".
 * @returns {Record<string, object>} Map of relative path to parsed schema
 */
function collectSchemas() {
  const schemas = {};

  const rootFiles = fs
    .readdirSync(SCHEMAS_DIR)
    .filter((f) => f.endsWith('.json'))
    .sort();
  for (const file of rootFiles) {
    schemas[file] = readJson(path.join(SCHEMAS_DIR, file));
  }

  if (fs.existsSync(TYPES_DIR)) {
    const typeFiles = fs
      .readdirSync(TYPES_DIR)
      .filter((f) => f.endsWith('.json'))
      .sort();
    for (const file of typeFiles) {
      schemas[`types/${file}`] = readJson(path.join(TYPES_DIR, file));
    }
  }

  return schemas;
}

/**
 * Read the fetched spec version from schemas/.version, if present.
 * @returns {string} Version string, or "unknown"
 */
function readSpecVersion() {
  try {
    return JSON.parse(fs.readFileSync(VERSION_FILE, 'utf-8')).version || 'unknown';
  } catch {
    return 'unknown';
  }
}

/**
 * Generate the TypeScript source for the bundled schemas module.
 * @param {Record<string, object>} schemas - Map of relative path to schema
 * @param {string} specVersion - xarf-spec version the schemas were taken from
 * @returns {string} TypeScript source
 */
function renderModule(schemas, specVersion) {
  const entries = Object.keys(schemas)
    .sort()
    .map((key) => `  ${JSON.stringify(key)}: ${JSON.stringify(schemas[key])},`)
    .join('\n');

  return `/* eslint-disable */
/**
 * AUTO-GENERATED FILE — DO NOT EDIT BY HAND.
 *
 * Generated by scripts/generate-schemas.js from the official xarf-spec schemas.
 * To refresh: \`npm run sync-schemas\` (fetches schemas, then regenerates this file).
 *
 * Source: xarf-spec ${specVersion}
 */

/**
 * Every XARF JSON schema, keyed by its relative path (matching the relative
 * \`$ref\` paths used inside the schemas), e.g. "xarf-core.json" and
 * "types/messaging-spam.json".
 */
export const bundledSchemas: Readonly<Record<string, Record<string, unknown>>> = Object.freeze({
${entries}
});

/** The xarf-spec version these bundled schemas were generated from. */
export const BUNDLED_SPEC_VERSION = ${JSON.stringify(specVersion)};
`;
}

/**
 * Main entry point.
 */
function main() {
  if (!fs.existsSync(path.join(SCHEMAS_DIR, 'xarf-core.json'))) {
    console.error(
      `[xarf] No schemas found at ${SCHEMAS_DIR}. Run "npm run fetch-schemas" first.`
    );
    process.exit(1);
  }

  const schemas = collectSchemas();
  const specVersion = readSpecVersion();
  const source = renderModule(schemas, specVersion);

  fs.writeFileSync(OUTPUT_FILE, source);
  console.log(
    `[xarf] Generated ${path.relative(process.cwd(), OUTPUT_FILE)} ` +
      `with ${Object.keys(schemas).length} schemas (xarf-spec ${specVersion}).`
  );
}

if (require.main === module) {
  main();
}

module.exports = { collectSchemas, renderModule };
